---
apiVersion: v1
kind: Service
metadata:
  name: gatekeeper-service
spec:
  selector:
    app: gatekeeper-app
  ports:
    - protocol: TCP
      port: 6000
      targetPort: 6000
  type: LoadBalancer