---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: manan-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
#  selector:
#    matchLabels:
#      app: temperature-retriever-app