---
apiVersion: v1
kind: Service
metadata:
  name: temperature-retriever-app-service
spec:
  selector:
    app: temperature-retriever-app
  ports:
    - protocol: TCP
      port: 6001
      targetPort: 6001
  type: ClusterIP
