---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: temperature-retriever-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: temperature-retriever-app
  template:
    metadata:
      labels:
        app: temperature-retriever-app
    spec:
      volumes:
        - name: manan-pvcd
          persistentVolumeClaim:
            claimName: manan-pvcd
      containers:
        - name: temperature-retriever-app-container
          image: us-east1-docker.pkg.dev/stoked-axe-388413/temperature-retriever-service/temperature-retriever-service
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 6001
          volumeMounts:
            - name: manan-pvcd
              mountPath: /manan_PV_dir
#          livenessProbe:
#            failureThreshold: 3
#            httpGet:
#              path: /actuator/info
#              port: 6000
#              scheme: HTTP
#            initialDelaySeconds: 60
#            periodSeconds: 60
#            successThreshold: 1
#            timeoutSeconds: 300
#          readinessProbe:
#            failureThreshold: 3
#            httpGet:
#              path: /actuator/health
#              port: 6000
#              scheme: HTTP
#            initialDelaySeconds: 60
#            periodSeconds: 60
#            successThreshold: 1
#            timeoutSeconds: 300